# Generated by Django 5.1.4 on 2025-01-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='std',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('course', models.TextField()),
            ],
        ),
    ]
